# Compote Config File

[engine]
force_cpu = false
models_dir = "./models"
default_model = "qwen-1-5b"
temperature = 0.17
seed = 1337

[isolation]
provider = "none" # "none", "docker", "podman"
image = "ghcr.io/compote/runtime-cuda:latest"
passthrough_gpu = true

[models.qwen-1-5b]
hf_repo = "Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF"
filename = "qwen2.5-coder-1.5b-instruct-q4_k_m.gguf"
tokenizer = "tokenizer.json"
max_context_tokens = 32768

[[rules]]
name = "big_doc_routing"
trigger_token_count = 4000
use_model = "qwen-1.5b"